/*
 * Flight Low-fare Search
 * # Introduction  The Flight Low-fare Search REST/JSON API is a traditional flight search API that enables you to find the best flight offers that match your search (one-way and round-trip) from a wide choice of airlines.  The result contains the flight details and will allow the user to select their preferred option based on either price or convenience. A wide range of search criteria can be applied to narrow the search results.  # Authorization  Before using the API you will need to get an access token. Please read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to get your token.  # Supported Operations  Resource: flight-offers  HTTP method: GET
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hr.ament.swagairfare.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * the query parameters for which default values were used are returned here
 */
@ApiModel(description = "the query parameters for which default values were used are returned here")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-18T23:02:34.311+02:00")
public class Defaults {
  @JsonProperty("nonStop")
  private Boolean nonStop = null;

  @JsonProperty("adults")
  private Integer adults = null;

  public Defaults nonStop(Boolean nonStop) {
    this.nonStop = nonStop;
    return this;
  }

   /**
   * search finds only direct flights going from the origin to the destination with no stop
   * @return nonStop
  **/
  @ApiModelProperty(example = "false", value = "search finds only direct flights going from the origin to the destination with no stop")
  public Boolean isNonStop() {
    return nonStop;
  }

  public void setNonStop(Boolean nonStop) {
    this.nonStop = nonStop;
  }

  public Defaults adults(Integer adults) {
    this.adults = adults;
    return this;
  }

   /**
   * search does the computation for one adult
   * @return adults
  **/
  @ApiModelProperty(example = "1", value = "search does the computation for one adult")
  public Integer getAdults() {
    return adults;
  }

  public void setAdults(Integer adults) {
    this.adults = adults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Defaults defaults = (Defaults) o;
    return Objects.equals(this.nonStop, defaults.nonStop) &&
        Objects.equals(this.adults, defaults.adults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nonStop, adults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Defaults {\n");
    
    sb.append("    nonStop: ").append(toIndentedString(nonStop)).append("\n");
    sb.append("    adults: ").append(toIndentedString(adults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

