/*
 * Flight Low-fare Search
 * # Introduction  The Flight Low-fare Search REST/JSON API is a traditional flight search API that enables you to find the best flight offers that match your search (one-way and round-trip) from a wide choice of airlines.  The result contains the flight details and will allow the user to select their preferred option based on either price or convenience. A wide range of search criteria can be applied to narrow the search results.  # Authorization  Before using the API you will need to get an access token. Please read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to get your token.  # Supported Operations  Resource: flight-offers  HTTP method: GET
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hr.ament.swagairfare.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hr.ament.swagairfare.client.model.OfferItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * FlightOffer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-18T23:02:34.311+02:00")
public class FlightOffer {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("offerItems")
  private List<OfferItem> offerItems = null;

  public FlightOffer type(String type) {
    this.type = type;
    return this;
  }

   /**
   * the resource name
   * @return type
  **/
  @ApiModelProperty(example = "flight-offer", value = "the resource name")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public FlightOffer id(String id) {
    this.id = id;
    return this;
  }

   /**
   * the resource identifier
   * @return id
  **/
  @ApiModelProperty(example = "12345", value = "the resource identifier")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FlightOffer offerItems(List<OfferItem> offerItems) {
    this.offerItems = offerItems;
    return this;
  }

  public FlightOffer addOfferItemsItem(OfferItem offerItemsItem) {
    if (this.offerItems == null) {
      this.offerItems = new ArrayList<OfferItem>();
    }
    this.offerItems.add(offerItemsItem);
    return this;
  }

   /**
   * Get offerItems
   * @return offerItems
  **/
  @ApiModelProperty(value = "")
  public List<OfferItem> getOfferItems() {
    return offerItems;
  }

  public void setOfferItems(List<OfferItem> offerItems) {
    this.offerItems = offerItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightOffer flightOffer = (FlightOffer) o;
    return Objects.equals(this.type, flightOffer.type) &&
        Objects.equals(this.id, flightOffer.id) &&
        Objects.equals(this.offerItems, flightOffer.offerItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, offerItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightOffer {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    offerItems: ").append(toIndentedString(offerItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

