/*
 * Flight Low-fare Search
 * # Introduction  The Flight Low-fare Search REST/JSON API is a traditional flight search API that enables you to find the best flight offers that match your search (one-way and round-trip) from a wide choice of airlines.  The result contains the flight details and will allow the user to select their preferred option based on either price or convenience. A wide range of search criteria can be applied to narrow the search results.  # Authorization  Before using the API you will need to get an access token. Please read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to get your token.  # Supported Operations  Resource: flight-offers  HTTP method: GET
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hr.ament.swagairfare.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hr.ament.swagairfare.client.model.AircraftEquipment;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * details of stops for direct or change of gauge flights
 */
@ApiModel(description = "details of stops for direct or change of gauge flights")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-18T23:02:34.311+02:00")
public class FlightStop {
  @JsonProperty("iataCode")
  private String iataCode = null;

  @JsonProperty("newAircraft")
  private AircraftEquipment newAircraft = null;

  @JsonProperty("duration")
  private String duration = null;

  @JsonProperty("arrivalAt")
  private OffsetDateTime arrivalAt = null;

  @JsonProperty("departureAt")
  private OffsetDateTime departureAt = null;

  public FlightStop iataCode(String iataCode) {
    this.iataCode = iataCode;
    return this;
  }

   /**
   * [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)
   * @return iataCode
  **/
  @ApiModelProperty(example = "JFK", value = "[IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)")
  public String getIataCode() {
    return iataCode;
  }

  public void setIataCode(String iataCode) {
    this.iataCode = iataCode;
  }

  public FlightStop newAircraft(AircraftEquipment newAircraft) {
    this.newAircraft = newAircraft;
    return this;
  }

   /**
   * Get newAircraft
   * @return newAircraft
  **/
  @ApiModelProperty(value = "")
  public AircraftEquipment getNewAircraft() {
    return newAircraft;
  }

  public void setNewAircraft(AircraftEquipment newAircraft) {
    this.newAircraft = newAircraft;
  }

  public FlightStop duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
   * @return duration
  **/
  @ApiModelProperty(example = "PT2H10M", value = "stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public FlightStop arrivalAt(OffsetDateTime arrivalAt) {
    this.arrivalAt = arrivalAt;
    return this;
  }

   /**
   * arrival at the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm±hh:mm format, e.g. 2017-02-10T20:40:00+02:00
   * @return arrivalAt
  **/
  @ApiModelProperty(example = "2017-10-23T20:00:00+02:00", value = "arrival at the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm±hh:mm format, e.g. 2017-02-10T20:40:00+02:00")
  public OffsetDateTime getArrivalAt() {
    return arrivalAt;
  }

  public void setArrivalAt(OffsetDateTime arrivalAt) {
    this.arrivalAt = arrivalAt;
  }

  public FlightStop departureAt(OffsetDateTime departureAt) {
    this.departureAt = departureAt;
    return this;
  }

   /**
   * departure from the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm±hh:mm format, e.g. 2017-02-10T20:40:00+02:00
   * @return departureAt
  **/
  @ApiModelProperty(example = "2017-10-23T20:00:00+02:00", value = "departure from the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm±hh:mm format, e.g. 2017-02-10T20:40:00+02:00")
  public OffsetDateTime getDepartureAt() {
    return departureAt;
  }

  public void setDepartureAt(OffsetDateTime departureAt) {
    this.departureAt = departureAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightStop flightStop = (FlightStop) o;
    return Objects.equals(this.iataCode, flightStop.iataCode) &&
        Objects.equals(this.newAircraft, flightStop.newAircraft) &&
        Objects.equals(this.duration, flightStop.duration) &&
        Objects.equals(this.arrivalAt, flightStop.arrivalAt) &&
        Objects.equals(this.departureAt, flightStop.departureAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iataCode, newAircraft, duration, arrivalAt, departureAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightStop {\n");
    
    sb.append("    iataCode: ").append(toIndentedString(iataCode)).append("\n");
    sb.append("    newAircraft: ").append(toIndentedString(newAircraft)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    arrivalAt: ").append(toIndentedString(arrivalAt)).append("\n");
    sb.append("    departureAt: ").append(toIndentedString(departureAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

