/*
 * Flight Low-fare Search
 * # Introduction  The Flight Low-fare Search REST/JSON API is a traditional flight search API that enables you to find the best flight offers that match your search (one-way and round-trip) from a wide choice of airlines.  The result contains the flight details and will allow the user to select their preferred option based on either price or convenience. A wide range of search criteria can be applied to narrow the search results.  # Authorization  Before using the API you will need to get an access token. Please read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to get your token.  # Supported Operations  Resource: flight-offers  HTTP method: GET
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hr.ament.swagairfare.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hr.ament.swagairfare.client.model.AircraftEquipment;
import hr.ament.swagairfare.client.model.FlightEndPoint;
import hr.ament.swagairfare.client.model.FlightStop;
import hr.ament.swagairfare.client.model.OperatingFlight;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * defining a flight segment; including both operating and marketing details when applicable
 */
@ApiModel(description = "defining a flight segment; including both operating and marketing details when applicable")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-18T23:02:34.311+02:00")
public class FlightSegment {
  @JsonProperty("departure")
  private FlightEndPoint departure = null;

  @JsonProperty("arrival")
  private FlightEndPoint arrival = null;

  @JsonProperty("carrierCode")
  private String carrierCode = null;

  @JsonProperty("number")
  private String number = null;

  @JsonProperty("aircraft")
  private AircraftEquipment aircraft = null;

  @JsonProperty("operating")
  private OperatingFlight operating = null;

  @JsonProperty("duration")
  private String duration = null;

  @JsonProperty("stops")
  private List<FlightStop> stops = null;

  public FlightSegment departure(FlightEndPoint departure) {
    this.departure = departure;
    return this;
  }

   /**
   * Get departure
   * @return departure
  **/
  @ApiModelProperty(value = "")
  public FlightEndPoint getDeparture() {
    return departure;
  }

  public void setDeparture(FlightEndPoint departure) {
    this.departure = departure;
  }

  public FlightSegment arrival(FlightEndPoint arrival) {
    this.arrival = arrival;
    return this;
  }

   /**
   * Get arrival
   * @return arrival
  **/
  @ApiModelProperty(value = "")
  public FlightEndPoint getArrival() {
    return arrival;
  }

  public void setArrival(FlightEndPoint arrival) {
    this.arrival = arrival;
  }

  public FlightSegment carrierCode(String carrierCode) {
    this.carrierCode = carrierCode;
    return this;
  }

   /**
   * providing the airline / carrier code
   * @return carrierCode
  **/
  @ApiModelProperty(example = "DL", value = "providing the airline / carrier code")
  public String getCarrierCode() {
    return carrierCode;
  }

  public void setCarrierCode(String carrierCode) {
    this.carrierCode = carrierCode;
  }

  public FlightSegment number(String number) {
    this.number = number;
    return this;
  }

   /**
   * the flight number as assigned by the carrier
   * @return number
  **/
  @ApiModelProperty(example = "212", value = "the flight number as assigned by the carrier")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public FlightSegment aircraft(AircraftEquipment aircraft) {
    this.aircraft = aircraft;
    return this;
  }

   /**
   * Get aircraft
   * @return aircraft
  **/
  @ApiModelProperty(value = "")
  public AircraftEquipment getAircraft() {
    return aircraft;
  }

  public void setAircraft(AircraftEquipment aircraft) {
    this.aircraft = aircraft;
  }

  public FlightSegment operating(OperatingFlight operating) {
    this.operating = operating;
    return this;
  }

   /**
   * Get operating
   * @return operating
  **/
  @ApiModelProperty(value = "")
  public OperatingFlight getOperating() {
    return operating;
  }

  public void setOperating(OperatingFlight operating) {
    this.operating = operating;
  }

  public FlightSegment duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
   * @return duration
  **/
  @ApiModelProperty(example = "PT2H10M", value = "stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public FlightSegment stops(List<FlightStop> stops) {
    this.stops = stops;
    return this;
  }

  public FlightSegment addStopsItem(FlightStop stopsItem) {
    if (this.stops == null) {
      this.stops = new ArrayList<FlightStop>();
    }
    this.stops.add(stopsItem);
    return this;
  }

   /**
   * information regarding the different stops composing the flight segment. E.g. technical stop, change of gauge...
   * @return stops
  **/
  @ApiModelProperty(value = "information regarding the different stops composing the flight segment. E.g. technical stop, change of gauge...")
  public List<FlightStop> getStops() {
    return stops;
  }

  public void setStops(List<FlightStop> stops) {
    this.stops = stops;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightSegment flightSegment = (FlightSegment) o;
    return Objects.equals(this.departure, flightSegment.departure) &&
        Objects.equals(this.arrival, flightSegment.arrival) &&
        Objects.equals(this.carrierCode, flightSegment.carrierCode) &&
        Objects.equals(this.number, flightSegment.number) &&
        Objects.equals(this.aircraft, flightSegment.aircraft) &&
        Objects.equals(this.operating, flightSegment.operating) &&
        Objects.equals(this.duration, flightSegment.duration) &&
        Objects.equals(this.stops, flightSegment.stops);
  }

  @Override
  public int hashCode() {
    return Objects.hash(departure, arrival, carrierCode, number, aircraft, operating, duration, stops);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightSegment {\n");
    
    sb.append("    departure: ").append(toIndentedString(departure)).append("\n");
    sb.append("    arrival: ").append(toIndentedString(arrival)).append("\n");
    sb.append("    carrierCode: ").append(toIndentedString(carrierCode)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    aircraft: ").append(toIndentedString(aircraft)).append("\n");
    sb.append("    operating: ").append(toIndentedString(operating)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    stops: ").append(toIndentedString(stops)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

