/*
 * Flight Low-fare Search
 * # Introduction  The Flight Low-fare Search REST/JSON API is a traditional flight search API that enables you to find the best flight offers that match your search (one-way and round-trip) from a wide choice of airlines.  The result contains the flight details and will allow the user to select their preferred option based on either price or convenience. A wide range of search criteria can be applied to narrow the search results.  # Authorization  Before using the API you will need to get an access token. Please read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to get your token.  # Supported Operations  Resource: flight-offers  HTTP method: GET
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hr.ament.swagairfare.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * an object containing references to the source of the error
 */
@ApiModel(description = "an object containing references to the source of the error")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-18T23:02:34.311+02:00")
public class IssueSource {
  @JsonProperty("pointer")
  private String pointer = null;

  @JsonProperty("parameter")
  private String parameter = null;

  @JsonProperty("example")
  private String example = null;

  public IssueSource pointer(String pointer) {
    this.pointer = pointer;
    return this;
  }

   /**
   * a JSON Pointer [RFC6901] to the associated entity in the request document
   * @return pointer
  **/
  @ApiModelProperty(value = "a JSON Pointer [RFC6901] to the associated entity in the request document")
  public String getPointer() {
    return pointer;
  }

  public void setPointer(String pointer) {
    this.pointer = pointer;
  }

  public IssueSource parameter(String parameter) {
    this.parameter = parameter;
    return this;
  }

   /**
   * a string indicating which URI query parameter caused the issue
   * @return parameter
  **/
  @ApiModelProperty(value = "a string indicating which URI query parameter caused the issue")
  public String getParameter() {
    return parameter;
  }

  public void setParameter(String parameter) {
    this.parameter = parameter;
  }

  public IssueSource example(String example) {
    this.example = example;
    return this;
  }

   /**
   * a string indicating an example of the right value
   * @return example
  **/
  @ApiModelProperty(value = "a string indicating an example of the right value")
  public String getExample() {
    return example;
  }

  public void setExample(String example) {
    this.example = example;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueSource issueSource = (IssueSource) o;
    return Objects.equals(this.pointer, issueSource.pointer) &&
        Objects.equals(this.parameter, issueSource.parameter) &&
        Objects.equals(this.example, issueSource.example);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pointer, parameter, example);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueSource {\n");
    
    sb.append("    pointer: ").append(toIndentedString(pointer)).append("\n");
    sb.append("    parameter: ").append(toIndentedString(parameter)).append("\n");
    sb.append("    example: ").append(toIndentedString(example)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

