/*
 * Flight Low-fare Search
 * # Introduction  The Flight Low-fare Search REST/JSON API is a traditional flight search API that enables you to find the best flight offers that match your search (one-way and round-trip) from a wide choice of airlines.  The result contains the flight details and will allow the user to select their preferred option based on either price or convenience. A wide range of search criteria can be applied to narrow the search results.  # Authorization  Before using the API you will need to get an access token. Please read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to get your token.  # Supported Operations  Resource: flight-offers  HTTP method: GET
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hr.ament.swagairfare.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hr.ament.swagairfare.client.model.FlightSegment;
import hr.ament.swagairfare.client.model.PricingDetail;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Segment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-18T23:02:34.311+02:00")
public class Segment {
  @JsonProperty("flightSegment")
  private FlightSegment flightSegment = null;

  @JsonProperty("pricingDetailPerAdult")
  private PricingDetail pricingDetailPerAdult = null;

  @JsonProperty("pricingDetailPerInfant")
  private PricingDetail pricingDetailPerInfant = null;

  @JsonProperty("pricingDetailPerChild")
  private PricingDetail pricingDetailPerChild = null;

  @JsonProperty("pricingDetailPerSenior")
  private PricingDetail pricingDetailPerSenior = null;

  public Segment flightSegment(FlightSegment flightSegment) {
    this.flightSegment = flightSegment;
    return this;
  }

   /**
   * Get flightSegment
   * @return flightSegment
  **/
  @ApiModelProperty(value = "")
  public FlightSegment getFlightSegment() {
    return flightSegment;
  }

  public void setFlightSegment(FlightSegment flightSegment) {
    this.flightSegment = flightSegment;
  }

  public Segment pricingDetailPerAdult(PricingDetail pricingDetailPerAdult) {
    this.pricingDetailPerAdult = pricingDetailPerAdult;
    return this;
  }

   /**
   * Get pricingDetailPerAdult
   * @return pricingDetailPerAdult
  **/
  @ApiModelProperty(value = "")
  public PricingDetail getPricingDetailPerAdult() {
    return pricingDetailPerAdult;
  }

  public void setPricingDetailPerAdult(PricingDetail pricingDetailPerAdult) {
    this.pricingDetailPerAdult = pricingDetailPerAdult;
  }

  public Segment pricingDetailPerInfant(PricingDetail pricingDetailPerInfant) {
    this.pricingDetailPerInfant = pricingDetailPerInfant;
    return this;
  }

   /**
   * Get pricingDetailPerInfant
   * @return pricingDetailPerInfant
  **/
  @ApiModelProperty(value = "")
  public PricingDetail getPricingDetailPerInfant() {
    return pricingDetailPerInfant;
  }

  public void setPricingDetailPerInfant(PricingDetail pricingDetailPerInfant) {
    this.pricingDetailPerInfant = pricingDetailPerInfant;
  }

  public Segment pricingDetailPerChild(PricingDetail pricingDetailPerChild) {
    this.pricingDetailPerChild = pricingDetailPerChild;
    return this;
  }

   /**
   * Get pricingDetailPerChild
   * @return pricingDetailPerChild
  **/
  @ApiModelProperty(value = "")
  public PricingDetail getPricingDetailPerChild() {
    return pricingDetailPerChild;
  }

  public void setPricingDetailPerChild(PricingDetail pricingDetailPerChild) {
    this.pricingDetailPerChild = pricingDetailPerChild;
  }

  public Segment pricingDetailPerSenior(PricingDetail pricingDetailPerSenior) {
    this.pricingDetailPerSenior = pricingDetailPerSenior;
    return this;
  }

   /**
   * Get pricingDetailPerSenior
   * @return pricingDetailPerSenior
  **/
  @ApiModelProperty(value = "")
  public PricingDetail getPricingDetailPerSenior() {
    return pricingDetailPerSenior;
  }

  public void setPricingDetailPerSenior(PricingDetail pricingDetailPerSenior) {
    this.pricingDetailPerSenior = pricingDetailPerSenior;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Segment segment = (Segment) o;
    return Objects.equals(this.flightSegment, segment.flightSegment) &&
        Objects.equals(this.pricingDetailPerAdult, segment.pricingDetailPerAdult) &&
        Objects.equals(this.pricingDetailPerInfant, segment.pricingDetailPerInfant) &&
        Objects.equals(this.pricingDetailPerChild, segment.pricingDetailPerChild) &&
        Objects.equals(this.pricingDetailPerSenior, segment.pricingDetailPerSenior);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flightSegment, pricingDetailPerAdult, pricingDetailPerInfant, pricingDetailPerChild, pricingDetailPerSenior);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Segment {\n");
    
    sb.append("    flightSegment: ").append(toIndentedString(flightSegment)).append("\n");
    sb.append("    pricingDetailPerAdult: ").append(toIndentedString(pricingDetailPerAdult)).append("\n");
    sb.append("    pricingDetailPerInfant: ").append(toIndentedString(pricingDetailPerInfant)).append("\n");
    sb.append("    pricingDetailPerChild: ").append(toIndentedString(pricingDetailPerChild)).append("\n");
    sb.append("    pricingDetailPerSenior: ").append(toIndentedString(pricingDetailPerSenior)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

